[build]
  command = "yarn build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_BASE_URL"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/tin-tuc/*"
  to = "/tin-tuc/:splat"
  status = 200
  force = true

  [redirects.rate_limit]
    action = "rewrite"
    to = "/truy-cap-qua-nhanh"
    window_limit = 120
    window_size = 60
    aggregate_by = ["ip", "domain"]

[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200
  force = true

  [redirects.rate_limit]
    action = "rewrite"
    to = "/truy-cap-qua-nhanh"
    window_limit = 120
    window_size = 60
    aggregate_by = ["ip", "domain"]
